.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "WAPITI\-GETCOOKIE" "1" "May 2026" ""
.SH "NAME"
\fBwapiti\-getcookie\fR \- A Wapiti utility to fetch cookies from a webpage and store them in the Wapiti JSON format\.
.SH "SYNOPSIS"
\fBwapiti\-getcookie\fR \-u \fIURL\fR \-c \fICOOKIE\fR \fIoptions\fR
.SH "DESCRIPTION"
wapiti\-getcookie is a user\-friendly interactive console utility that can be used to fill a web\-form or fetch a URL and extract the cookies sent by the remote server\.
.br
Cookie information are stored in the JSON cookie file you have to specify with the \-c option\.
.br
Those cookies can be loaded by Wapiti using the same \-c option\.
.SH "OPTIONS"
.IP "\(bu" 4
\fB\-u\fR, \fB\-\-url\fR \fIURL\fR
.br
First page to fetch for cookies\.
.IP "\(bu" 4
\fB\-c\fR, \fB\-\-cookie\fR \fICOOKIE_FILE\fR
.br
Cookie file in Wapiti JSON format where cookies will be stored\.
.IP "\(bu" 4
\fB\-p\fR, \fB\-\-proxy\fR \fIPROXY_URL\fR
.br
The given URL will be used as a proxy for HTTP and HTTPS requests\.
.br
This URL can have one of the following scheme : http, https, socks, socks5\.
.IP "\(bu" 4
\fB\-\-tor\fR
.br
Make Wapiti use a Tor listener (same as \-\-proxy socks://127\.0\.0\.1:9050/)
.IP "\(bu" 4
\fB\-a\fR, \fB\-\-auth\-cred\fR \fICREDENTIALS\fR
.br
(DEPRECATED) Set credentials to use for HTTP authentication on the target\.
.br
Given value should be in the form login%password (% is used as a separator)\.
.IP "\(bu" 4
\fB\-\-auth\-user\fR \fIUSERNAME\fR Set HTTP authentication username\.
.IP "\(bu" 4
\fB\-\-auth\-password\fR \fIPASSWORD\fR Set HTTP authentication password\.
.IP "\(bu" 4
\fB\-\-auth\-method\fR \fITYPE\fR Set the authentication mechanism to use\. Valid choices are basic, digest and ntlm (default is basic)\.
.br
NTLM authentication may require you to install an additional Python module\.
.IP "\(bu" 4
\fB\-\-form\-data\fR \fIDATA\fR
.br
wapiti\-getcookie will parse forms and ask your input for each field found\.
.br
But you can also pass every parameter and value as a string directly through this option\.
.br
Example: \-\-form\-data 'login=admin&password=letmein&submit=Login'
.IP "\(bu" 4
\fB\-\-form\-enctype\fR \fIENCTYPE\fR Set enctype to use to POST form data to form URL (default is application/x\-www\-form\-urlencoded)\.
.IP "\(bu" 4
\fB\-\-headless\fR \fIMODE\fR Use a Firefox headless crawler for browsing (slower)\. Valid choices are no, hidden, visible (default is no)\.
.IP "\(bu" 4
\fB\-H\fR, \fB\-\-header\fR \fIHEADER\fR
.br
Set a custom HTTP header to inject in every request sent by Wapiti\. This option can be used several times\.
.br
Value should be a standard HTTP header line (parameter and value separated with a : sign)\.
.IP "\(bu" 4
\fB\-A\fR, \fB\-\-user\-agent\fR \fIAGENT\fR
.br
Default behavior of Wapiti is to use a modernized Firefox User\-Agent\.
.br
You can change it to bypass some restrictions or for better compatibility\.
.IP "" 0
.SH "LICENSE"
Wapiti is covered by the GNU General Public License (GPL), version 2\. Please read the LICENSE file for more information\.
.SH "COPYRIGHT"
Copyright (c) 2006\-2026 Nicolas Surribas\.
.SH "AUTHORS"
Nicolas Surribas is the main author, but the whole list of contributors is found in the separate AUTHORS file\.
.SH "WWW"
https://wapiti\-scanner\.github\.io/
.SH "BUG REPORTS"
If you find a bug in Wapiti please report it to https://github\.com/wapiti\-scanner/wapiti/issues
