.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WAPITI\-GETCOOKIE" "1" "October 2022" "" ""
.
.SH "NAME"
\fBwapiti\-getcookie\fR \- A Wapiti utility to fetch cookies from a webpage and store them in the Wapiti JSON format\.
.
.SH "SYNOPSIS"
\fBwapiti\-getcookie\fR \-u \fIURL\fR \-c \fICOOKIE\fR \fIoptions\fR
.
.SH "DESCRIPTION"
wapiti\-getcookie is a user\-friendly interactive console utility that can be used to fill a web\-form or fetch a URL and extract the cookies sent by the remote server\.
.
.br
Cookie information are stored in the JSON cookie file you have to specify with the \-c option\.
.
.br
Those cookies can be loaded by Wapiti using the same \-c option\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-p\fR, \fB\-\-proxy\fR \fIPROXY_URL\fR
.
.br
The given URL will be used as a proxy for HTTP and HTTPS requests\.
.
.br
This URL can have one of the following scheme : http, https, socks\.
.
.br
To make Wapiti use a Tor listener you can use \-\-proxy socks://127\.0\.0\.1:9050/
.
.IP "\(bu" 4
\fB\-\-tor\fR
.
.br
Make Wapiti use a Tor listener (same as \-\-proxy socks://127\.0\.0\.1:9050/)
.
.IP "\(bu" 4
\fB\-a\fR, \fB\-\-auth\-cred\fR \fICREDENTIALS\fR
.
.br
Set credentials to use for HTTP authentication on the target\.
.
.br
Given value should be in the form login%password (% is used as a separator)
.
.IP "\(bu" 4
\fB\-\-auth\-method\fR \fITYPE\fR Set the authentication mechanism to use\. Valid choices are basic, digest and ntlm\.
.
.br
NTLM authentication may require you to install an additional Python module\.
.
.IP "\(bu" 4
\fB\-H\fR, \fB\-\-header\fR \fIHEADER\fR
.
.br
Set a custom HTTM header to inject in every request sent by Wapiti\. This option can be used several times\.
.
.br
Value should be a standard HTTP header line (parameter and value separated with a : sign)\.
.
.IP "\(bu" 4
\fB\-A\fR, \fB\-\-user\-agent\fR \fIAGENT\fR
.
.br
Default behavior of Wapiti is to use the same User\-Agent as the TorBrowser, making it discreet when crawling standard website or \.onion ones\.
.
.br
But you may have to change it to bypass some restrictions so this option is here\.
.
.IP "\(bu" 4
\fB\-d\fR, \fB\-\-data\fR \fIDATA\fR
.
.br
wapiti\-getcookie will parse forms and ask your input for each field found\.
.
.br
But you can also pass every parameter and value as a string directly through this option\.
.
.br
Example: \-d \'login=admin&password=letmein&submit=Login\'
.
.IP "" 0
.
.SH "LICENSE"
Wapiti is covered by the GNU General Public License (GPL), version 2\. Please read the LICENSE file for more information\.
.
.SH "COPYRIGHT"
Copyright (c) 2006\-2023 Nicolas Surribas\.
.
.SH "AUTHORS"
Nicolas Surribas is the main author, but the whole list of contributors is found in the separate AUTHORS file\.
.
.SH "WWW"
https://wapiti\-scanner\.github\.io/
.
.SH "BUG REPORTS"
If you find a bug in Wapiti please report it to https://github\.com/wapiti\-scanner/wapiti/issues
